/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadAPP;

import accesoAdatos.Coneccion;
import accesoAdatos.MateriaData;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import universidadAPP.Entidades.Materia;

/**
 *
 * @author perey
 */
public class FormularioMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        initComponents();
        jRestadoMat.setSelected(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbn = new javax.swing.JButton();
        jbg = new javax.swing.JButton();
        jbs = new javax.swing.JButton();
        jtcodigo = new javax.swing.JTextField();
        jtnom = new javax.swing.JTextField();
        jtaño = new javax.swing.JTextField();
        jbb = new javax.swing.JButton();
        jRestadoMat = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Formulario de Materias");

        jLabel2.setText("Codigo :");

        jLabel3.setText("Nombre :");

        jLabel4.setText("Año ;");

        jLabel5.setText("Estado :");

        jbn.setText("Nueva Materia");
        jbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnActionPerformed(evt);
            }
        });

        jbg.setText("Modificar");
        jbg.setEnabled(false);
        jbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgActionPerformed(evt);
            }
        });

        jbs.setText("Salir");
        jbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsActionPerformed(evt);
            }
        });

        jbb.setText("Nueva Busqueda");
        jbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbActionPerformed(evt);
            }
        });

        jRestadoMat.setSelected(true);

        jLabel6.setText("Activa / Inactiva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jbn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnom)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbb))
                                    .addComponent(jtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRestadoMat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 132, Short.MAX_VALUE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbb))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRestadoMat)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbn)
                    .addComponent(jbg)
                    .addComponent(jbs))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsActionPerformed

    private void jbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnActionPerformed
        //ESTE ES EL CODIGO AL APRETAR EL BOTON NUEVA MATERIA
        
        // Validaciones varias
        // Como usamos un mismo formulario para varias acciones, es posible que se intente agregar
        // una materia (apretando el boton de agregar) mientras esta habilitado el cuadro de texto
        // de Id Materia, debajo, chequea eso y en el caso que haya algo escrito, avisa que no será tenido
        // en cuenta ya que el codigo de materia lo asigna el sistema automaticamente
        String idMat=jtcodigo.getText();
        if  (!idMat.isEmpty()){
            JOptionPane.showMessageDialog(this,"El codigo de materia se agregará automaticamente por el sistema");
            jtcodigo.setText(null);
        }
        
        // Debajo se valida que se ingrese una nombre de materia y un año
        String nomMat=jtnom.getText();
        boolean estadoMat=true;
        int añoM=1;
        if (nomMat.isEmpty()){
           JOptionPane.showMessageDialog(this,"Debe ingresar un nombre de materia");
           return;
        }else {
            String añoMat=jtaño.getText();
            if (añoMat.isEmpty()){
                JOptionPane.showMessageDialog(this,"Debe ingresar el año de la materia");
                return;
            }else {
                añoM=Integer.parseInt(añoMat);
                if( jRestadoMat.isSelected()){
                  estadoMat=true;
                }else estadoMat=false;
                }
            
            //Debajo creo una materia con los datos obtenidos del formulario (ya validados)
            Materia nueva=new Materia(nomMat,añoM,estadoMat);
            
            //Debajo creo un objeto MateriaData para acceder a los metodos
            MateriaData mat=new MateriaData();
            
            //Debajo compruebo si la materia que se quiere agregar ya existe
            //utilizando el metodo buscarNombreMateria
            boolean encontrado=mat.buscarNombreMateria(nueva);
            if (encontrado==true){
                JOptionPane.showMessageDialog(this,"Esa materia ya existe");
                return;
            }else{
                //Como el resultado de la busqueda es negativo, llamo al metodo GuardarMateria y limpio el 
                //formulario
                mat.guardarMateria(nueva);} 
                limpiarForm();
    
    }//GEN-LAST:event_jbnActionPerformed
    }
    
    private void jbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbActionPerformed
        //ESTE ES EL CODIGO AL APRETAR EL BOTON BUSCAR
        
        String codMat=jtcodigo.getText();
        //Nuevamente, usar un mismo formulario para varias acciones puede traer problemas
        //aqui se intenta establecer si el usuario esta queriendo agregar o modificar una nueva materia
        //por eso se trata de controlar la accesibilidad a los distintos botones o cuadros de texto segun 
        //que esté haciendo el usuario
        
        boolean estadobot=jtcodigo.isEnabled();
        
        if (estadobot!=true){
            jtcodigo.setEnabled(true);
            limpiarForm();
            jbg.setEnabled(false);
            return;
        }
        //Devajo se valida que haya algun codigo escrito a buscar        
        int idMat=0;
        if (codMat.isEmpty()){
            JOptionPane.showMessageDialog(this,"Debe ingresar el codigo de la materia a buscar");
        }else{
             try {
                idMat= Integer.parseInt(codMat);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Revise el codigo ingresado");
                jtcodigo.setText(null);
                return;
            }
        
            String nomMat="";
            boolean estMat=true;
            MateriaData mat=new MateriaData();
            jtcodigo.setEnabled(false);
    
        
        //Habiendo atravesado las valicaciones, se procede a buscar los datos para completar el formulario
        //Se pudo haber hecho con un metodo dentro de Materia Data... pero me di cuenta despues de hacerlo
        
            String sql= "SELECT * FROM materia Where Idmateria= ?";
            PreparedStatement ps;
            try {
                ps = (PreparedStatement) mat.con.prepareStatement(sql);
                ps.setInt(1, idMat);
                ResultSet rs=ps.executeQuery();
                while (rs.next()){
                    jtnom.setText(rs.getString(2));
                    jtaño.setText(rs.getString(3));
                    estMat=rs.getBoolean(4);
                    if(estMat==true){
                        jRestadoMat.setSelected(true);
                    }else {
                        jRestadoMat.setSelected(false);
                        }
                    jbg.setEnabled(true);
                    jtcodigo.setEnabled(false);
                }
                rs.close();
                ps.close();
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this,"Error buscando la materia");
           }
                                   

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbbActionPerformed

    private void jbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgActionPerformed
        //ESTE ES EL CODIGO DEL BOTON MODIFICAR
        //Aquí toma la información de los cuadros de texto y del radio buton y llama al metodo
        //modificar materia de Materia Data
        
        String nomMat=jtnom.getText();
        String añoM=(jtaño.getText());
        //Validaciones para que no haya campos vacios
        if(nomMat.isEmpty()){
            JOptionPane.showMessageDialog(this,"El campo nombre no puede estar vacío");
            jtnom.requestFocus();
            return;
        }
        
        if(añoM.isEmpty()){
            JOptionPane.showMessageDialog(this,"El campo año no puede estar vacío");
            jtaño.requestFocus();
            return;
        }
        
        //Creo un nuevo objeto Materia Data con el cual acceder a los metodos
        MateriaData mat=new MateriaData();
        int idMat=0;
        try{
            idMat=Integer.parseInt(jtcodigo.getText());
        }catch (NumberFormatException r){
            JOptionPane.showMessageDialog(this,"Error, codigo materia cambiado o erroneo");
            jtcodigo.setText(null);
            return;
           }
                      
            boolean estMat;
            if (jRestadoMat.isSelected()){
                estMat=true;
            }else{
                estMat=false;
                }
            int añoMat=Integer.parseInt(añoM);
            //Aca creo una nueva Materia, con los datos tomados del formulario
            Materia modMat=new Materia(idMat,nomMat,añoMat,estMat);
            //Llamo al método modificar Materia, pasando como parametro la "Materia" creada arriba
            mat.modificarMateria(modMat);
            limpiarForm();
            jbg.setEnabled(false);
        
    }//GEN-LAST:event_jbgActionPerformed
    

        
        
    
        
    
    
        
        
        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRestadoMat;
    private javax.swing.JButton jbb;
    private javax.swing.JButton jbg;
    private javax.swing.JButton jbn;
    private javax.swing.JButton jbs;
    private javax.swing.JTextField jtaño;
    private javax.swing.JTextField jtcodigo;
    private javax.swing.JTextField jtnom;
    // End of variables declaration//GEN-END:variables

public void limpiarForm(){
//metodo para limpiar el formulario
jtcodigo.setText("");
jtnom.setText("");
jtaño.setText("");
jRestadoMat.setSelected(false);




    
}
}
