/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadAPP;

import accesoAdatos.AlumnoData;
import accesoAdatos.InscripcionData;
import accesoAdatos.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadAPP.Entidades.Ealumno;
import universidadAPP.Entidades.Inscripcion;
import universidadAPP.Entidades.Materia;

/**
 *
 * @author perey
 */
public class FormularioInscripciones extends javax.swing.JInternalFrame {

    
    private ArrayList<Materia>listaM;
    private ArrayList<Ealumno>listaA;
    
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoData aData;
    
    private DefaultTableModel modelo;
    
    /**
     * Creates new form FormularioInscripciones
     */
    public FormularioInscripciones() {
        initComponents();
    
        aData =new AlumnoData();
        listaA= (ArrayList<Ealumno>)aData.ListarAlumnos();
        modelo= new DefaultTableModel();
        inscData = new InscripcionData();
        mData = new MateriaData ();
        cargarAlumnos();
        armarCabecera();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbAlumno = new javax.swing.JComboBox<>();
        jrbmnoincript = new javax.swing.JRadioButton();
        jrbminscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFincripcion = new javax.swing.JTable();
        jbinscribir = new javax.swing.JButton();
        jbanular = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText("Seleccione un alumno :");

        jLabel3.setText("Listado de Materias");

        jrbmnoincript.setText("Materias no inscriptas");
        jrbmnoincript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmnoincriptActionPerformed(evt);
            }
        });

        jrbminscriptas.setText("Materias inscriptas");
        jrbminscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbminscriptasActionPerformed(evt);
            }
        });

        jtFincripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtFincripcion);

        jbinscribir.setText("Inscribir");
        jbinscribir.setEnabled(false);
        jbinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinscribirActionPerformed(evt);
            }
        });

        jbanular.setText("Anular inscripcion");
        jbanular.setEnabled(false);
        jbanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanularActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jrbminscriptas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbmnoincript)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbinscribir)
                .addGap(64, 64, 64)
                .addComponent(jbanular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbmnoincript)
                    .addComponent(jrbminscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbinscribir)
                    .addComponent(jbanular)
                    .addComponent(jbSalir))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbminscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbminscriptasActionPerformed
        borrarfilasT();
        jrbmnoincript.setSelected(false);
       cargadDatosInsciptos();
      jbanular.setEnabled(true);
        jbinscribir.setEnabled(false);
         
    }//GEN-LAST:event_jrbminscriptasActionPerformed

    private void jrbmnoincriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmnoincriptActionPerformed
        borrarfilasT();
        jrbminscriptas.setSelected(false);

        cargadDatosNInscriptos();
         jbinscribir.setEnabled(true);
        jbanular.setEnabled(false);
//        
    }//GEN-LAST:event_jrbmnoincriptActionPerformed

    private void jbinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinscribirActionPerformed
  int fs=jtFincripcion.getSelectedRow();
       if(fs!=-1){
          Ealumno a=(Ealumno)jcbAlumno.getSelectedItem();
          
          int idMat=(Integer)modelo.getValueAt(fs, 0);
          String mat=(String)modelo.getValueAt(fs,1);
          int amat=(Integer)modelo.getValueAt(fs, 2);
          
          Materia m = new Materia(idMat , mat,amat,true);
             Inscripcion i = new Inscripcion(0,a,m);     
        inscData.guardarInscripcion(i);
        borrarfilasT();
       }
       
    }//GEN-LAST:event_jbinscribirActionPerformed

    private void jbanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanularActionPerformed
       int fs=jtFincripcion.getSelectedRow();
       if(fs!=-1){
          Ealumno a=(Ealumno)jcbAlumno.getSelectedItem();
         
          int idMat=(Integer)modelo.getValueAt(fs, 0);

                
             inscData.borrarInscripcionMateriaAlumno(a.getIdAlumno(), idMat);
             borrarfilasT();
       }
        
              
    
    }//GEN-LAST:event_jbanularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbanular;
    private javax.swing.JButton jbinscribir;
    private javax.swing.JComboBox<Ealumno> jcbAlumno;
    private javax.swing.JRadioButton jrbminscriptas;
    private javax.swing.JRadioButton jrbmnoincript;
    private javax.swing.JTable jtFincripcion;
    // End of variables declaration//GEN-END:variables
private void cargarAlumnos(){
for(Ealumno item:listaA){
//    String aux = item.getDni()+"-"+item.getApellido()+"-"+item.getNombre();
    jcbAlumno.addItem(item);
}
}
private void armarCabecera(){
    ArrayList<Object>filaCabecera = new ArrayList<>();
    filaCabecera.add("ID");
     filaCabecera.add("Nombre");
      filaCabecera.add("Año");
      for (Object i:filaCabecera){
          modelo.addColumn(i);
      }
      jtFincripcion.setModel(modelo);
}
      private void borrarfilasT(){
          int ind= modelo.getRowCount()-1;
          for (int x=ind ;x>=0;x--){
              modelo.removeRow(x);
              
          }
          
      }  
      private void cargadDatosNInscriptos(){
          //borrarfilasT();
          Ealumno eleg=(Ealumno)jcbAlumno.getSelectedItem();
          listaM =(ArrayList)inscData.obtenerMateriasNocursadas(eleg.getIdAlumno());
          for(Materia m:listaM){
              modelo.addRow(new Object[]{m.getIdMateria(),m.getNombre(),m.getAño()});
              
          }
          
      }
      private void cargadDatosInsciptos(){
          //borrarfilasT
          Ealumno eleg=(Ealumno)jcbAlumno.getSelectedItem();
          ArrayList<Materia> list=(ArrayList)inscData.obtenerMateriasCursadas(eleg.getIdAlumno());
           for(Materia m:list){
              modelo.addRow(new Object[]{m.getIdMateria(),m.getNombre(),m.getAño()});
      }
}
}
